CREATE TYPE "public"."dingorg_audit_actor_type" AS ENUM('api_key', 'dingtalk', 'system');--> statement-breakpoint
CREATE TYPE "public"."dingorg_audit_status" AS ENUM('success', 'failure');--> statement-breakpoint
CREATE TABLE "dingorg_audit_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "dingorg_audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_type" "dingorg_audit_actor_type" DEFAULT 'system' NOT NULL,
	"actor_id" varchar(255),
	"actor_name" varchar(255),
	"action" varchar(96) NOT NULL,
	"status" "dingorg_audit_status" DEFAULT 'success' NOT NULL,
	"target_type" varchar(64) NOT NULL,
	"target_id" varchar(255),
	"target_name" varchar(255),
	"ip" varchar(64),
	"user_agent" text,
	"method" varchar(8),
	"path" varchar(512),
	"request_id" varchar(64),
	"details" jsonb
);
--> statement-breakpoint
CREATE TABLE "dingorg_oidc_payloads" (
	"model" text NOT NULL,
	"id" text NOT NULL,
	"payload" jsonb NOT NULL,
	"grant_id" text,
	"uid" text,
	"expires_at" timestamp with time zone,
	"consumed_at" timestamp with time zone,
	CONSTRAINT "dingorg_oidc_payloads_model_id_pk" PRIMARY KEY("model","id")
);
--> statement-breakpoint
CREATE TABLE "dingorg_org_snapshots" (
	"app_key" text PRIMARY KEY NOT NULL,
	"data" jsonb,
	"fetched_at" timestamp with time zone,
	"attempted_at" timestamp with time zone NOT NULL,
	"error" text,
	"user_count" integer DEFAULT 0 NOT NULL,
	"dept_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dingorg_app_secrets" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "audit_log_at_idx" ON "dingorg_audit_log" USING btree ("at");--> statement-breakpoint
CREATE INDEX "audit_log_actor_idx" ON "dingorg_audit_log" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX "audit_log_action_idx" ON "dingorg_audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "audit_log_target_idx" ON "dingorg_audit_log" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX "audit_log_request_id_idx" ON "dingorg_audit_log" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX "oidc_payloads_grant_id_idx" ON "dingorg_oidc_payloads" USING btree ("grant_id");--> statement-breakpoint
CREATE INDEX "oidc_payloads_uid_idx" ON "dingorg_oidc_payloads" USING btree ("uid");--> statement-breakpoint
CREATE INDEX "oidc_payloads_expires_at_idx" ON "dingorg_oidc_payloads" USING btree ("expires_at");